"""empty message

Revision ID: 2306e6ea10d6
Revises: adcd43cb7b6c
Create Date: 2017-01-12 17:22:56.193788

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '2306e6ea10d6'
down_revision = 'adcd43cb7b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firstClassifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('一级分类名', sa.Unicode(length=255), nullable=True),
    sa.Column('创建时间', sa.DateTime(), nullable=True),
    sa.Column('修改时间', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('一级分类名')
    )
    op.create_table('secondaryClassifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('二级分类名', sa.Unicode(length=255), nullable=True),
    sa.Column('first_classification', sa.Integer(), nullable=True),
    sa.Column('创建时间', sa.DateTime(), nullable=True),
    sa.Column('修改时间', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['first_classification'], ['firstClassifications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('二级分类名')
    )
    op.create_table('functions',
    sa.Column('主键', sa.Integer(), nullable=False),
    sa.Column('功能名', sa.Unicode(length=255), nullable=True),
    sa.Column('secondary_classification', sa.Integer(), nullable=True),
    sa.Column('创建时间', sa.DateTime(), nullable=True),
    sa.Column('修改时间', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['secondary_classification'], ['secondaryClassifications.id'], ),
    sa.PrimaryKeyConstraint('\u4e3b\u952e'),
    sa.UniqueConstraint('功能名')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('functions')
    op.drop_table('secondaryClassifications')
    op.drop_table('firstClassifications')
    # ### end Alembic commands ###
