"""empty message

Revision ID: 3e73399f8616
Revises: 441e78e8bc9e
Create Date: 2017-01-10 20:40:27.496136

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e73399f8616'
down_revision = '441e78e8bc9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('Identifier', table_name='packages')
    op.drop_column('packages', 'Chunk数目')
    op.drop_column('packages', 'RelativePath')
    op.drop_column('packages', 'Identifier')
    op.drop_column('packages', '是否完整')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('是否完整', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('packages', sa.Column('Identifier', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('packages', sa.Column('RelativePath', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('packages', sa.Column('Chunk数目', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('Identifier', 'packages', ['Identifier'], unique=True)
    # ### end Alembic commands ###
