"""empty message

Revision ID: 441e78e8bc9e
Revises: 61bddc90b347
Create Date: 2017-01-09 14:37:58.334591

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '441e78e8bc9e'
down_revision = '61bddc90b347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('主键', sa.Integer(), nullable=False),
    sa.Column('文件名', sa.Unicode(length=255), nullable=True),
    sa.Column('RelativePath', sa.String(length=255), nullable=True),
    sa.Column('Identifier', sa.String(length=255), nullable=True),
    sa.Column('文件总大小', sa.Integer(), nullable=True),
    sa.Column('Chunk数目', sa.Integer(), nullable=True),
    sa.Column('是否完整', sa.Boolean(), nullable=True),
    sa.Column('MD5', sa.String(length=255), nullable=True),
    sa.Column('创建时间', sa.DateTime(), nullable=True),
    sa.Column('修改时间', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('\u4e3b\u952e'),
    sa.UniqueConstraint('Identifier')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('packages')
    # ### end Alembic commands ###
