"""init

Revision ID: 61bddc90b347
Revises: ea6953c65f34
Create Date: 2016-12-28 15:13:03.604518

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61bddc90b347'
down_revision = 'ea6953c65f34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('littleclouds', 'Fuck')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('littleclouds', sa.Column('Fuck', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
