"""empty message

Revision ID: 6c128af86770
Revises: e1fafb9bb332
Create Date: 2017-02-13 11:20:59.544486

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '6c128af86770'
down_revision = 'e1fafb9bb332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('littlecloud_appgroup',
    sa.Column('littlecloud_id', sa.Integer(), nullable=True),
    sa.Column('appgroup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appgroup_id'], ['appgroups.id'], ),
    sa.ForeignKeyConstraint(['littlecloud_id'], ['littleclouds.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('littlecloud_appgroup')
    # ### end Alembic commands ###
