"""empty message

Revision ID: adcd43cb7b6c
Revises: 3e73399f8616
Create Date: 2017-01-11 16:01:42.512354

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'adcd43cb7b6c'
down_revision = '3e73399f8616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'packages', ['文件名'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'packages', type_='unique')
    # ### end Alembic commands ###
