"""empty message

Revision ID: e1fafb9bb332
Revises: d5d15406b5ca
Create Date: 2017-02-07 17:16:13.016643

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'e1fafb9bb332'
down_revision = 'd5d15406b5ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appgroups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('应用组名', sa.Unicode(length=255), nullable=True),
    sa.Column('描述', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('应用组名'),
    sa.UniqueConstraint('描述')
    )
    op.create_table('appgroup_application',
    sa.Column('appgroup_id', sa.Integer(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appgroup_id'], ['appgroups.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appgroup_application')
    op.drop_table('appgroups')
    # ### end Alembic commands ###
