"""init

Revision ID: ea6953c65f34
Revises: dc56c1670276
Create Date: 2016-12-28 15:12:39.408192

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'ea6953c65f34'
down_revision = 'dc56c1670276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('littleclouds', sa.Column('Fuck', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('littleclouds', 'Fuck')
    # ### end Alembic commands ###
